export const AllowedMimetypes = {
  'image/png': true,
  'image/bmp': true,
  'image/jpg': true,
  'image/jpeg': true,
  'application/pdf': true,
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': true,
  'application/msword': true,
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': true,
  'application/vnd.openxmlformats-officedocument.presentationml.presentation': true,
  'video/mp4': true,
  'video/webm': true,
  'video/ogg': true,
  'video/quicktime': true,
  'video/x-: truemsvideo': true,
  'audio/mpeg': true,
  'audio/wav': true,
  'audio/ogg': true,
  'audio/mp4': true,
  'audio/m4a': true,
};
